export * from './Navbar'
export * from './Header'
export * from './Footer'
export * from './Home'
export * from './People'
export * from './Contacts'
export * from './Movies'
export * from './Details'
